#!/usr/bin/env python
# EXAMPLE CODE BELOW

from map import *
from tactic import *

context(ENGLAND)
set('nor')
fleet_hold('nor')
fleet_hold('lon')
army_hold('yor')

context(ITALY)
set('tun')
set('gas')
set('mar')
set('spa')
army_move('gas', 'spa')
fleet_support_move('lyo', 'gas', 'spa')
fleet_move_failed('ion', 'tun')
army_support_move('mar', 'gas', 'spa')

context(FRANCE)
army_hold('par')
fleet_hold('nth')
dislodge('spa')
fleet_move_failed('wes', 'tun')
set('naf')
set('por')

context(GERMANY)
fleet_move('den', 'bal')
army_move_failed('hol', 'bel')
army_move_failed('mun', 'sil')
fleet_move_failed('swe', 'nor')
army_move('trl', 'ven')
army_support_move('ber', 'mun', 'sil')
army_support_move('boh', 'mun', 'sil')
dislodge('boh')
set('hol')
set('den')
set('swe')
set('ven')

context(RUSSIA)
army_hold('bud')
army_move('gal', 'boh')
fleet_support_move('bot', 'lvn', 'stp')
army_move('lvn', 'stp')
army_move_failed('pru', 'ber')
army_support_move('sil', 'boh', 'gal')
set('boh')
set('sil')
set('gal')
set('pru')
set('bud')
set('rum')

context(AUSTRIA)
army_move_failed('gre', 'bul')
army_support_move('vie', 'gal', 'boh')
dislodge('gre')
set('alb')
set('vie')

context(TURKEY)
fleet_move('aeg', 'gre')
army_move_failed('con', 'bul')
fleet_move_failed('eas', 'ion')
army_support_move('ser', 'aeg', 'gre')
set('bul')
set('ser')
set('gre')

print(new_zombie_attack('bud'))
print(new_roads_to_sc('ENG'))
print(roads_to_sc('ENG'))
done()
